version: '3.8'
services:
  gateway:
    build: gateway
    image: gateway-image
    container_name: gateway-container
    ports:
      - "8080:8080"
    depends_on:
      - server
    environment:
      - SHAREIT_SERVER_URL=http://server:9090
      - GATEWAY_PORT=8080
#      - TZ=Europe/Moscow

  server:
    build: server
    image: server-image
    container_name: server-container
    ports:
      - "9090:9090"
    depends_on:
      - db
    environment:
      - DB_PORT=5432
      - POSTGRES_USERNAME=shareit
      - POSTGRES_PASSWORD=shareit
      - SERVER_PORT=9090
#      - TZ=Europe/Moscow

  db:
    image: postgres:14-alpine
    container_name: db
    restart: always
    ports:
      - "6541:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=shareit
      - POSTGRES_USER=shareit
      - POSTGRES_PASSWORD=shareit
#      - TZ=Europe/Moscow
    hostname: db

