DROP TABLE IF EXISTS users;

DROP TABLE IF EXISTS requests;

DROP TABLE IF EXISTS items;

DROP TABLE IF EXISTS bookings;

DROP TABLE IF EXISTS comments;

CREATE TABLE IF NOT EXISTS users
(
    user_id   int8 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_name varchar,
    email     varchar,
    CONSTRAINT uq_email UNIQUE (email)
);

CREATE TABLE IF NOT EXISTS requests
(
    request_id       int8 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    description      varchar,
    requester_id     int8 REFERENCES users (user_id),
    created_datetime TIMESTAMP WITHOUT TIME ZONE
);

CREATE TABLE IF NOT EXISTS items
(
    item_id         int8 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    item_name       varchar,
    description     varchar,
    is_available    boolean,
    owner_id        int8 REFERENCES users (user_id),
    item_request_id int8 REFERENCES requests (request_id)
);

CREATE TABLE IF NOT EXISTS bookings
(
    booking_id      int8 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    start_date      TIMESTAMP WITHOUT TIME ZONE,
    end_date        TIMESTAMP WITHOUT TIME ZONE,
    booking_item_id int8 REFERENCES items (item_id),
    booker_id       int8 REFERENCES users (user_id),
    status          varchar
);

CREATE TABLE IF NOT EXISTS comments
(
    comment_id       int8 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    comment_text     varchar,
    comment_item_id  int8 REFERENCES items (item_id),
    author_id        int8 REFERENCES users (user_id),
    created_datetime TIMESTAMP WITHOUT TIME ZONE
);